## Com llegir dades desde arxiu

Els arxius separats per comes (i salts de linea) es poden llegir amb la funció `readcsv`


#### `edge_list` com Array de Arrays

In [1]:
file_name = "graph0.in"

"graph0.in"

In [2]:
array_of_strings = readlines(file_name)
n_nodes, n_edges = split(array_of_strings[1], " ")
n_nodes = parse(Int64, n_nodes)
n_edges = parse(Int64, n_edges)

edge_list = Array{Array{Int64},1}()

for line in array_of_strings[2:end]
    push!(edge_list, parse.(Int64, split(line," ")))
end

In [3]:
edge_list

4-element Array{Array{Int64,N} where N,1}:
 [0, 1]
 [1, 2]
 [0, 3]
 [3, 1]

#### `edge_list` com a matriu de files o columnes

Podem escriure edge_list com a matriu 

In [4]:
array_of_strings = readlines(file_name)
n_nodes, n_edges = split(array_of_strings[1], " ")
n_nodes = parse(Int64, n_nodes)
n_edges = parse(Int64, n_edges)

edge_list = zeros(Int64, 2, n_edges)

for j in 1:n_edges
    edge_list[:,j] = parse.(Int64, split(array_of_strings[j+1]," "))
end

In [5]:
edge_list

2×4 Array{Int64,2}:
 0  1  0  3
 1  2  3  1

In [6]:
array_of_strings = readlines(file_name)
n_nodes, n_edges = split(array_of_strings[1], " ")
n_nodes = parse(Int64, n_nodes)
n_edges = parse(Int64, n_edges)

edge_list = zeros(Int64, n_edges,2)

for j in 1:n_edges
    edge_list[j, :] = parse.(Int64, split(array_of_strings[j+1]," "))
end

In [7]:
edge_list

4×2 Array{Int64,2}:
 0  1
 1  2
 0  3
 3  1

# Definim un tipo Graph

In [14]:
using LightGraphs

In [308]:
#immutable GraphAdjM(n_nodes, AdjMatrix)
#   n_nodes
#end

#### TODO

Observem que la funció retorna un `Array` que hem de parsejar.


La funció `graph_read_edge_list` llegeix un graph de l'arxiu `file_name` i retorna un graph_edge_list.




La funció `graphM_read` llegeix un graph de l-arxiu `file_name` i retorna la seva matriu d'adjacencia.

